server:
  port: 8083

spring:
  application:
    name: order-service

firestore:
  project-id: ${FIRESTORE_PROJECT_ID:cloud-module-490703}
  orders-collection: ${FIRESTORE_ORDERS_COLLECTION:orders}

storage:
  provider: ${STORAGE_PROVIDER:gcs} # local | gcs
  gcs:
    project-id: ${GCS_PROJECT_ID:cloud-module-490703}
    bucket: ${GCS_BUCKET:prod_bucket1234}

management:
  endpoints:
    web:
      exposure:
        include: health,info
