server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: product-service

firestore:
  project-id: ${FIRESTORE_PROJECT_ID:project-054ecf27-18a8-4d69-906}
  products-collection: ${FIRESTORE_PRODUCTS_COLLECTION:products}

storage:
  provider: ${STORAGE_PROVIDER:gcs} # local | gcs
  local:
    base-dir: ${LOCAL_STORAGE_DIR:./data/uploads}
  gcs:
    project-id: ${GCS_PROJECT_ID:project-054ecf27-18a8-4d69-906}
    bucket: ${GCS_BUCKET:cloths_bucket}

management:
  endpoints:
    web:
      exposure:
        include: health,info
