server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://34.171.127.81:3306/userdb?useSSL=true&requireSSL=true&useInformationSchema=false
    username: root
    password: My_sql1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # changed default dialect from H2 to MySQL8 so Hibernate won't expect H2/sequence metadata
    database-platform: ${USER_DB_DIALECT:org.hibernate.dialect.MySQL8Dialect}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET:12312312312312212212121211212221211211}
    issuer: ${JWT_ISSUER:eca-mini-ecommerce}
    expires-minutes: ${JWT_EXPIRES_MINUTES:240}

management:
  endpoints:
    web:
      exposure:
        include: health,info